language: php

php:
  - 7.4
  - 8.1

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-interaction

script: bin/kahlan --coverage=3 --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    -  secure: L5BucjQeYgnEDg9UJfNRxSp6l1lKcJqRjZxmbQQiGKw7x1nRi/IDsLcY4WG0VlrCRKsgRPo/3oBu3U7cbkm32KRiuzwiuc8bcz2HlEDOCup5wvLR+iVpiEXqz38bIhKQqkneJFo54AnDOHgePRxUz+K/jXAYjbr8tQOHXWalbIg=
